### ISSUE TITLE
Warnings with Numpy version 1.11.1

### ISSUE THREAD

**Issue by varenius** [daniellefenech/SERPent#2]
I am running SERPent 1.0 on Ubuntu 16.04 with a fairly recent version of Numpy. Although everything seems to work, I see the following type of messages flashing by many times:
```
 Max value < kickout. Skipping run...
/usr/local/lib/python2.7/dist-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/lib/function_base.py:3569: RuntimeWarning: Invalid value encountered in median
  RuntimeWarning)
 Max value < kickout. Skipping run...
```
I suppose this is some kind of check, because the flagging seems to run without stopping. But, perhaps it would be nice to update the code to get rid of this warning in the future.

**Comment by daniellefenech** [comment]
This warning does not affect the flagging process and has now been screened so should no longer be seen.
