### ISSUE TITLE
Default flagging options fail

### ISSUE THREAD

**Issue by varenius** [daniellefenech/SERPent#3]
I tried to run SERPent using 
flagging_options = 'choose'
in "SERPent_input.py", but it crashes:

 ALL baselines have been selected for flagging...
System Memory Information:
Total Memory  :    16.419 GB
Used Memory   :    421.692 MB
Free Memory   :    164.456 MB
Total Swap    :    23.726 GB
Total predicted memory usage: 2.609 GB
Traceback (most recent call last):
  File "SERPent.py", line 3429, in <module>
    parameters = source_base_parms[sdi]
IndexError: list index out of range

I tried to read the code, and it seems that "source_base_parms" is not set in the default mode. But, if I instead use flagging_options = 'choose', then it runs. If the options saved in the input-in the github repo are the default, then it's equivalet. But it would be good for a software with a "default" option to run with that option.

**Comment by daniellefenech** [comment]
Hi Eskil,


Thanks for letting me know about that. I'm actually just trying to sort 
out a few bugs associated with how the parameters are being passed through 
the code, so I'll add that to the mix, while I'm at it.


Please do let me know how you're getting on with it in terms of your data 
and settings etc. though, it really fdoes help!

Thanks,

Danielle



-------------------------------------------------
Dr. Danielle Fenech
Department of Physics and Astronomy,
University College London,
Gower Street,
London WC1E 6BT, UK


Tel: +44 (0)20 3549 5822
Fax: +44 (0)20 3549 5846
Email: dmf@star.ucl.ac.uk
-------------------------------------------------

**Comment by daniellefenech** [comment]
I've now updated the default settings with the recent changes and these should run without failing.
